[workspace]
members = [
  "air",
  "assembly",
  "core",
  "examples",
  "miden",
  "processor",
  "stdlib",
  "verifier"
]

[profile.release]
codegen-units = 1
lto = true

[profile.bench]
codegen-units = 1
lto = true
