[package]
name = "miden"
version = "0.2.0"
description="Miden virtual machine"
authors = ["miden contributors"]
readme="README.md"
license = "MIT"
repository = "https://github.com/maticnetwork/miden"
categories = ["cryptography", "emulators", "no-std"]
keywords = ["miden", "stark", "virtual-machine", "zkp"]
edition = "2021"
rust-version = "1.57"

[lib]
name = "miden"
path = "src/lib.rs"
bench = false
doctest = false

[features]
concurrent = ["prover/concurrent", "std"]
default = ["std"]
std = ["air/std", "assembly/std", "hex/std", "processor/std", "prover/std", "verifier/std"]

[dependencies]
air = { package = "miden-air", path = "../air", version = "0.2", default-features = false }
assembly = { package = "miden-assembly", path = "../assembly", version = "0.2", default-features = false }
processor = { package = "miden-processor", path = "../processor", version = "0.2", default-features = false }
prover = { package = "winter-prover", version = "0.3", default-features = false }
hex = { version = "0.4", optional = true }
log = { version = "0.4", default-features = false }
verifier = { package = "miden-verifier", path = "../verifier", version = "0.2", default-features = false }
vm-core = { package = "miden-core", path = "../core", version = "0.2", default-features = false }

[dev-dependencies]
blake3 = "1.3.1"
num-bigint = "0.4"
proptest = "1.0.0"
rand-utils = { package = "winter-rand-utils", version = "0.3" }
sha2 = "0.10.2"
sha3 = "0.10.1"
